### ISSUE TITLE
bot constantly crashing

### ISSUE THREAD

**Issue by orangebutblue** [JagandeepBrar/Telegram-Binance-Script#1]
```
2021-03-19T08:33:46: Traceback (most recent call last):
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
2021-03-19T08:33:46:     chunked=chunked)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
2021-03-19T08:33:46:     six.raise_from(e, None)
2021-03-19T08:33:46:   File "<string>", line 3, in raise_from
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
2021-03-19T08:33:46:     httplib_response = conn.getresponse()
2021-03-19T08:33:46:   File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
2021-03-19T08:33:46:     response.begin()
2021-03-19T08:33:46:   File "/usr/lib/python3.7/http/client.py", line 306, in begin
2021-03-19T08:33:46:     version, status, reason = self._read_status()
2021-03-19T08:33:46:   File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
2021-03-19T08:33:46: line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2021-03-19T08:33:46:   File "/usr/lib/python3.7/socket.py", line 589, in readinto
2021-03-19T08:33:46:     return self._sock.recv_into(b)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 309, in recv_into
2021-03-19T08:33:46:     return self.recv_into(*args, **kwargs)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
2021-03-19T08:33:46:     raise SocketError(str(e))
2021-03-19T08:33:46: OSError: (104, 'ECONNRESET')
2021-03-19T08:33:46:
2021-03-19T08:33:46: Traceback (most recent call last):
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
2021-03-19T08:33:46:     timeout=timeout
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
2021-03-19T08:33:46:     _stacktrace=sys.exc_info()[2])
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
2021-03-19T08:33:46:     raise six.reraise(type(error), error, _stacktrace)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
2021-03-19T08:33:46:     raise value.with_traceback(tb)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
2021-03-19T08:33:46:     chunked=chunked)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
2021-03-19T08:33:46:     six.raise_from(e, None)
2021-03-19T08:33:46:   File "<string>", line 3, in raise_from
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
2021-03-19T08:33:46:     httplib_response = conn.getresponse()
2021-03-19T08:33:46:   File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
2021-03-19T08:33:46:     response.begin()
2021-03-19T08:33:46:   File "/usr/lib/python3.7/http/client.py", line 306, in begin
2021-03-19T08:33:46:     version, status, reason = self._read_status()
2021-03-19T08:33:46:   File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
2021-03-19T08:33:46:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2021-03-19T08:33:46:   File "/usr/lib/python3.7/socket.py", line 589, in readinto
2021-03-19T08:33:46:     return self._sock.recv_into(b)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 309, in recv_into
2021-03-19T08:33:46:     return self.recv_into(*args, **kwargs)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
2021-03-19T08:33:46:     raise SocketError(str(e))
2021-03-19T08:33:46: urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))
2021-03-19T08:33:46:
2021-03-19T08:33:46: During handling of the above exception, another exception occurred:
2021-03-19T08:33:46:
2021-03-19T08:33:46: Traceback (most recent call last):
2021-03-19T08:33:46:   File "/opt/Telegram-Binance-Script/start.py", line 127, in <module>
2021-03-19T08:33:46:     start()
2021-03-19T08:33:46:   File "/opt/Telegram-Binance-Script/start.py", line 27, in start
2021-03-19T08:33:46:     process()
2021-03-19T08:33:46:   File "/opt/Telegram-Binance-Script/start.py", line 89, in process
2021-03-19T08:33:46:     open_orders = binance_bot.get_open_orders()
2021-03-19T08:33:46:   File "/usr/local/lib/python3.7/dist-packages/binance/client.py", line 1727, in get_open_orders
2021-03-19T08:33:46:     return self._get('openOrders', True, data=params)
2021-03-19T08:33:46:   File "/usr/local/lib/python3.7/dist-packages/binance/client.py", line 237, in _get
2021-03-19T08:33:46:     return self._request_api('get', path, signed, version, **kwargs)
2021-03-19T08:33:46:   File "/usr/local/lib/python3.7/dist-packages/binance/client.py", line 202, in _request_api
2021-03-19T08:33:46:     return self._request(method, uri, signed, **kwargs)
2021-03-19T08:33:46:   File "/usr/local/lib/python3.7/dist-packages/binance/client.py", line 196, in _request
2021-03-19T08:33:46:     self.response = getattr(self.session, method)(uri, **kwargs)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
2021-03-19T08:33:46:     return self.request('GET', url, **kwargs)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
2021-03-19T08:33:46:     resp = self.send(prep, **send_kwargs)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
2021-03-19T08:33:46:     r = adapter.send(request, **kwargs)
2021-03-19T08:33:46:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
2021-03-19T08:33:46:     raise ConnectionError(err, request=request)
2021-03-19T08:33:46: requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))

```

**Comment by JagandeepBrar** [comment]
Apologies, but this bot no longer has any support or maintenance, and the Binance API has likely changed a lot since development, rendering it useless.
